# Generated by Django 2.1.5 on 2019-02-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_foodweight")]

    operations = [
        migrations.AlterField(
            model_name="foodweight",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        )
    ]
