# Generated by Django 2.1.5 on 2019-02-09 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_auto_20190209_1959")]

    operations = [
        migrations.AlterField(
            model_name="foodweight",
            name="amount",
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name="foodweight",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weight",
                to="core.Food",
            ),
        ),
        migrations.AlterField(
            model_name="foodweight",
            name="weight",
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
