# Generated by Django 2.1.7 on 2019-04-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_food_raw_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
